# -*- coding: utf-8 -*-
"""CNN-urban-LCZ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TwvOr7TUwEZp6gCkZPuUx2H6ATUxgHye
"""

import os
import time
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import rasterio
from rasterio.warp import reproject, Resampling
from scipy import ndimage
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader


# =====================================================
# USER SETTINGS
# =====================================================

LCZ_PATH = "/content/drive/MyDrive/LCZ-LST_analysis/LCZ_Urban_CONUS_2020_2km.tif"
LST_PATH = "/content/drive/MyDrive/LCZ-LST_analysis/LST_CONUS_2020_2km.tif"
OUTPUT_DIR = "/content/drive/MyDrive/LCZ_LST_CNN_CONUS_results_no_coordinates"

SEED = 8
WINDOW_SIZE = 9
PATCH_SIZE_CNN = 9

TRAIN_RATIO = 0.70
VAL_RATIO = 0.10

MAX_TRAIN_PIXELS = 200_000
MAX_VAL_PIXELS = 40_000
MAX_TEST_PIXELS = 40_000

CNN_EPOCHS = 100
CNN_BATCH_SIZE = 128
CNN_LR = 1e-3
CNN_WEIGHT_DECAY = 1e-5
CNN_PATIENCE = 20

PREDICT_FULL_MAP = True
FULL_MAP_BATCH_SIZE = 2048

os.makedirs(OUTPUT_DIR, exist_ok=True)


# =====================================================
# REPRODUCIBILITY
# =====================================================

def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

set_seed(SEED)

DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print("Using device:", DEVICE)
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))


# =====================================================
# LOAD AND ALIGN RASTERS
# =====================================================

def read_and_match_target_to_lcz(lcz_path, target_path):
    with rasterio.open(lcz_path) as src_lcz:
        lcz = src_lcz.read(1).astype(np.float32)
        lcz_profile = src_lcz.profile

    with rasterio.open(target_path) as src_target:
        target_matched = np.empty(lcz.shape, dtype=np.float32)

        reproject(
            source=rasterio.band(src_target, 1),
            destination=target_matched,
            src_transform=src_target.transform,
            src_crs=src_target.crs,
            dst_transform=lcz_profile["transform"],
            dst_crs=lcz_profile["crs"],
            resampling=Resampling.bilinear,
        )

    return lcz, target_matched, lcz_profile


lcz_array, lst_array, lcz_profile = read_and_match_target_to_lcz(LCZ_PATH, LST_PATH)

H, W = lcz_array.shape

valid_mask = (
    (lcz_array > 0) &
    (lcz_array <= 17) &
    np.isfinite(lst_array)
)

valid_indices = np.where(valid_mask.ravel())[0]

print("LCZ shape:", lcz_array.shape)
print("Target shape:", lst_array.shape)
print("Valid pixels:", len(valid_indices))
print("Target range:", float(np.nanmin(lst_array)), float(np.nanmax(lst_array)))


# =====================================================
# LIGHT LANDSCAPE METRICS
# =====================================================

def calculate_PLAND(lcz_array, window_size, lcz_classes=range(1, 18)):
    pland = np.zeros(
        (lcz_array.shape[0], lcz_array.shape[1], len(list(lcz_classes))),
        dtype=np.float32
    )

    for i, lcz_class in enumerate(lcz_classes):
        binary_mask = (lcz_array == lcz_class).astype(np.float32)
        pland[:, :, i] = ndimage.uniform_filter(binary_mask, size=window_size)

    return pland


def calculate_SHDI(lcz_array, window_size):
    def shannon_diversity(window):
        valid = window[(window > 0) & (window <= 17)]
        if valid.size == 0:
            return 0.0
        _, counts = np.unique(valid, return_counts=True)
        p = counts / counts.sum()
        return -np.sum(p * np.log(p + 1e-8))

    return ndimage.generic_filter(
        lcz_array,
        shannon_diversity,
        size=window_size
    ).astype(np.float32)


def calculate_PD(lcz_array, window_size):
    def count_patches(window):
        valid = window[(window > 0) & (window <= 17)]
        if valid.size == 0:
            return 0.0
        return len(np.unique(valid)) / (window_size * window_size)

    return ndimage.generic_filter(
        lcz_array,
        count_patches,
        size=window_size
    ).astype(np.float32)


def build_feature_stack(lcz_array, window_size):
    print("Calculating lightweight feature maps without coordinates...")

    H, W = lcz_array.shape

    pland = calculate_PLAND(lcz_array, window_size)
    shdi = calculate_SHDI(lcz_array, window_size)
    pdens = calculate_PD(lcz_array, window_size)

    # Heavy metrics disabled for large CONUS-scale data
    contag = np.zeros((H, W), dtype=np.float32)
    shape_am = np.zeros((H, W), dtype=np.float32)
    teci = np.zeros((H, W), dtype=np.float32)
    ai = np.zeros((H, W), dtype=np.float32)

    feature_maps = [
        contag,
        shdi,
        shape_am,
        teci,
        ai,
        pdens
    ]

    feature_names = [
        "CONTAG_zero",
        "SHDI",
        "SHAPE_AM_zero",
        "TECI_zero",
        "AI_zero",
        "PD"
    ]

    existing_lcz = [int(c) for c in np.unique(lcz_array) if 1 <= c <= 17]

    for cls in existing_lcz:
        fmap = pland[:, :, cls - 1].copy()
        fmap[lcz_array == cls] = 1.0
        feature_maps.append(fmap.astype(np.float32))
        feature_names.append(f"PLAND_LCZ_{cls}")

    stack = np.stack(feature_maps, axis=0).astype(np.float32)
    stack = np.nan_to_num(stack, nan=0.0, posinf=0.0, neginf=0.0)

    print("Feature stack:", stack.shape)
    print("Feature names:", feature_names)

    return stack, feature_names


feature_stack, feature_names = build_feature_stack(lcz_array, WINDOW_SIZE)


# =====================================================
# RANDOM SPLIT + SUBSAMPLING
# =====================================================

def create_random_split(valid_indices, seed, train_ratio=0.6, val_ratio=0.1):
    set_seed(seed)

    n = len(valid_indices)
    perm = torch.randperm(n).cpu().numpy()

    n_train = int(n * train_ratio)
    n_val = int(n * val_ratio)

    train_pos = perm[:n_train]
    val_pos = perm[n_train:n_train + n_val]
    test_pos = perm[n_train + n_val:]

    train_indices = valid_indices[train_pos]
    val_indices = valid_indices[val_pos]
    test_indices = valid_indices[test_pos]

    return train_indices, val_indices, test_indices


train_indices, val_indices, test_indices = create_random_split(
    valid_indices,
    seed=SEED,
    train_ratio=TRAIN_RATIO,
    val_ratio=VAL_RATIO
)

rng = np.random.default_rng(SEED)

train_indices = rng.choice(
    train_indices,
    size=min(MAX_TRAIN_PIXELS, len(train_indices)),
    replace=False
)

val_indices = rng.choice(
    val_indices,
    size=min(MAX_VAL_PIXELS, len(val_indices)),
    replace=False
)

test_indices = rng.choice(
    test_indices,
    size=min(MAX_TEST_PIXELS, len(test_indices)),
    replace=False
)

print("\n=== SUBSAMPLED RANDOM SPLIT ===")
print("Training pixels:", len(train_indices))
print("Validation pixels:", len(val_indices))
print("Test pixels:", len(test_indices))


# =====================================================
# DATASET
# =====================================================

class PatchDataset(Dataset):
    def __init__(self, feature_stack, target_array, flat_indices, patch_size=9):
        self.feature_stack = feature_stack
        self.target_array = target_array
        self.flat_indices = np.asarray(flat_indices)
        self.patch_size = patch_size
        self.pad = patch_size // 2
        self.C, self.H, self.W = feature_stack.shape

        self.padded = np.pad(
            feature_stack,
            ((0, 0), (self.pad, self.pad), (self.pad, self.pad)),
            mode="edge"
        )

    def __len__(self):
        return len(self.flat_indices)

    def __getitem__(self, idx):
        flat = int(self.flat_indices[idx])
        r = flat // self.W
        c = flat % self.W

        rp = r + self.pad
        cp = c + self.pad

        patch = self.padded[
            :,
            rp - self.pad:rp + self.pad + 1,
            cp - self.pad:cp + self.pad + 1
        ]

        y = self.target_array[r, c]

        return (
            torch.tensor(patch, dtype=torch.float32),
            torch.tensor(y, dtype=torch.float32)
        )


# =====================================================
# CNN MODEL
# =====================================================

class SimplePatchCNN(nn.Module):
    def __init__(self, in_channels, dropout=0.25):
        super().__init__()

        self.net = nn.Sequential(
            nn.Conv2d(in_channels, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),

            nn.Conv2d(32, 48, kernel_size=3, padding=1),
            nn.BatchNorm2d(48),
            nn.ReLU(),

            nn.Conv2d(48, 48, kernel_size=3, padding=1),
            nn.BatchNorm2d(48),
            nn.ReLU(),

            nn.AdaptiveAvgPool2d(1),
            nn.Flatten(),

            nn.Dropout(dropout),
            nn.Linear(48, 64),
            nn.ReLU(),

            nn.Dropout(dropout),
            nn.Linear(64, 1),
        )

    def forward(self, x):
        return self.net(x).squeeze(-1)


def count_trainable_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)


def regression_metrics(y_true, y_pred):
    y_true = np.asarray(y_true).ravel()
    y_pred = np.asarray(y_pred).ravel()

    return {
        "R2": float(r2_score(y_true, y_pred)),
        "RMSE": float(np.sqrt(mean_squared_error(y_true, y_pred))),
        "MAE": float(mean_absolute_error(y_true, y_pred)),
    }


# =====================================================
# TRAINING
# =====================================================

def train_cnn(train_indices, val_indices, test_indices, seed):
    set_seed(seed)

    train_ds = PatchDataset(feature_stack, lst_array, train_indices, PATCH_SIZE_CNN)
    val_ds = PatchDataset(feature_stack, lst_array, val_indices, PATCH_SIZE_CNN)
    test_ds = PatchDataset(feature_stack, lst_array, test_indices, PATCH_SIZE_CNN)

    train_loader = DataLoader(
        train_ds,
        batch_size=CNN_BATCH_SIZE,
        shuffle=True,
        num_workers=0,
        pin_memory=torch.cuda.is_available()
    )

    val_loader = DataLoader(
        val_ds,
        batch_size=CNN_BATCH_SIZE,
        shuffle=False,
        num_workers=0,
        pin_memory=torch.cuda.is_available()
    )

    test_loader = DataLoader(
        test_ds,
        batch_size=CNN_BATCH_SIZE,
        shuffle=False,
        num_workers=0,
        pin_memory=torch.cuda.is_available()
    )

    model = SimplePatchCNN(in_channels=feature_stack.shape[0]).to(DEVICE)

    print(f"CNN input channels: {feature_stack.shape[0]}")
    print(f"CNN trainable parameters: {count_trainable_parameters(model):,}")

    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=CNN_LR,
        weight_decay=CNN_WEIGHT_DECAY
    )

    loss_fn = nn.MSELoss()

    best_state = None
    best_val = float("inf")
    patience_count = 0

    train_losses = []
    val_losses = []

    for epoch in range(CNN_EPOCHS):
        t0 = time.time()

        model.train()
        batch_losses = []

        for xb, yb in train_loader:
            xb = xb.to(DEVICE)
            yb = yb.to(DEVICE)

            optimizer.zero_grad()
            pred = model(xb)
            loss = loss_fn(pred, yb)

            loss.backward()
            optimizer.step()

            batch_losses.append(loss.item())

        model.eval()
        val_batch_losses = []

        with torch.no_grad():
            for xb, yb in val_loader:
                xb = xb.to(DEVICE)
                yb = yb.to(DEVICE)

                pred = model(xb)
                val_loss = loss_fn(pred, yb)

                val_batch_losses.append(val_loss.item())

        train_loss = float(np.mean(batch_losses))
        val_loss = float(np.mean(val_batch_losses))

        train_losses.append(train_loss)
        val_losses.append(val_loss)

        if val_loss < best_val:
            best_val = val_loss
            best_state = {
                k: v.detach().cpu().clone()
                for k, v in model.state_dict().items()
            }
            patience_count = 0
        else:
            patience_count += 1

        if epoch % 10 == 0 or epoch == CNN_EPOCHS - 1:
            print(
                f"Epoch {epoch:03d} | "
                f"train MSE: {train_loss:.4f} | "
                f"val MSE: {val_loss:.4f} | "
                f"time: {time.time() - t0:.2f}s"
            )

        if patience_count >= CNN_PATIENCE:
            print(f"Early stopping at epoch {epoch}")
            break

    if best_state is not None:
        model.load_state_dict(best_state)

    preds = []
    targets = []

    model.eval()

    with torch.no_grad():
        for xb, yb in test_loader:
            xb = xb.to(DEVICE)

            pred = model(xb).cpu().numpy()

            preds.append(pred)
            targets.append(yb.numpy())

    preds = np.concatenate(preds)
    targets = np.concatenate(targets)

    metrics = regression_metrics(targets, preds)

    return model, metrics, preds, targets, train_losses, val_losses


print("\n================ TRAINING CNN WITHOUT COORDINATES ================")

cnn_model, cnn_metrics, cnn_pred, cnn_target, cnn_train_losses, cnn_val_losses = train_cnn(
    train_indices,
    val_indices,
    test_indices,
    seed=SEED
)

print("\n=== CNN TEST METRICS ===")
print(cnn_metrics)


# =====================================================
# SAVE MODEL AND METRICS
# =====================================================

model_path = os.path.join(OUTPUT_DIR, f"CNN_no_coordinates_seed_{SEED}.pt")
torch.save(cnn_model.state_dict(), model_path)

metrics_df = pd.DataFrame([{
    "Validation": "Random subsampled pixel split",
    "Seed": SEED,
    "Model": "CNN_no_coordinates",
    "Train_pixels": len(train_indices),
    "Val_pixels": len(val_indices),
    "Test_pixels": len(test_indices),
    "Input_channels": feature_stack.shape[0],
    **cnn_metrics
}])

metrics_csv = os.path.join(OUTPUT_DIR, "CNN_no_coordinates_metrics.csv")
metrics_df.to_csv(metrics_csv, index=False)


# =====================================================
# LOSS CURVE
# =====================================================

plt.figure(figsize=(6, 4))
plt.plot(cnn_train_losses, label="CNN train")
plt.plot(cnn_val_losses, label="CNN validation")
plt.xlabel("Epoch")
plt.ylabel("MSE loss")
plt.title("CNN loss curve without coordinates")
plt.legend()
plt.tight_layout()

loss_plot = os.path.join(OUTPUT_DIR, "CNN_no_coordinates_loss_curve.png")
plt.savefig(loss_plot, dpi=300, bbox_inches="tight")
plt.show()


# =====================================================
# PREDICTION FUNCTION
# =====================================================

def predict_indices(model, flat_indices, batch_size=2048):
    ds = PatchDataset(feature_stack, lst_array, flat_indices, PATCH_SIZE_CNN)

    loader = DataLoader(
        ds,
        batch_size=batch_size,
        shuffle=False,
        num_workers=0,
        pin_memory=torch.cuda.is_available()
    )

    preds = []
    targets = []

    model.eval()

    with torch.no_grad():
        for xb, yb in loader:
            xb = xb.to(DEVICE)
            pred = model(xb).cpu().numpy()

            preds.append(pred)
            targets.append(yb.numpy())

    return np.concatenate(preds), np.concatenate(targets)


# =====================================================
# FINAL FIGURE
# =====================================================

print("\nPredicting train, validation, and test samples for scatter plot...")

train_preds, train_targets = predict_indices(cnn_model, train_indices, batch_size=2048)
val_preds, val_targets = predict_indices(cnn_model, val_indices, batch_size=2048)
test_preds, test_targets = predict_indices(cnn_model, test_indices, batch_size=2048)

test_r2 = r2_score(test_targets, test_preds)

if PREDICT_FULL_MAP:
    print("\nPredicting full valid map...")
    full_indices = valid_indices
    full_preds, full_targets = predict_indices(
        cnn_model,
        full_indices,
        batch_size=FULL_MAP_BATCH_SIZE
    )
else:
    print("\nUsing sampled pixels only for map...")
    full_indices = np.concatenate([train_indices, val_indices, test_indices])
    full_preds, full_targets = predict_indices(
        cnn_model,
        full_indices,
        batch_size=FULL_MAP_BATCH_SIZE
    )

true_map = np.full(lcz_array.shape, np.nan, dtype=np.float32)
pred_map = np.full(lcz_array.shape, np.nan, dtype=np.float32)

rows = full_indices // W
cols = full_indices % W

true_map[rows, cols] = full_targets
pred_map[rows, cols] = full_preds

vmin = np.nanpercentile(true_map, 2)
vmax = np.nanpercentile(true_map, 98)

transform = lcz_profile["transform"]

xmin = transform.c
xmax = transform.c + transform.a * W
ymax = transform.f
ymin = transform.f + transform.e * H

extent = [xmin, xmax, ymin, ymax]

fig, axes = plt.subplots(1, 3, figsize=(18, 5), dpi=300)

im0 = axes[0].imshow(
    true_map,
    cmap="Spectral_r",
    vmin=vmin,
    vmax=vmax,
    extent=extent
)

axes[0].set_title("True LST")
axes[0].set_xlabel("Longitude")
axes[0].set_ylabel("Latitude")

plt.colorbar(
    im0,
    ax=axes[0],
    fraction=0.046,
    pad=0.04,
    label="LST (°C)"
)

im1 = axes[1].imshow(
    pred_map,
    cmap="Spectral_r",
    vmin=vmin,
    vmax=vmax,
    extent=extent
)

axes[1].set_title("Predicted LST - CNN")
axes[1].set_xlabel("Longitude")
axes[1].set_ylabel("Latitude")

plt.colorbar(
    im1,
    ax=axes[1],
    fraction=0.046,
    pad=0.04,
    label="LST (°C)"
)

axes[2].scatter(
    train_targets,
    train_preds,
    s=5,
    alpha=0.35,
    label="Train"
)

axes[2].scatter(
    val_targets,
    val_preds,
    s=5,
    alpha=0.45,
    label="Validation"
)

sc = axes[2].scatter(
    test_targets,
    test_preds,
    c=test_targets,
    cmap="Spectral_r",
    s=5,
    alpha=0.65,
    label="Test"
)

lo = min(test_targets.min(), test_preds.min())
hi = max(test_targets.max(), test_preds.max())

axes[2].plot(
    [lo, hi],
    [lo, hi],
    "k--",
    linewidth=1.2,
    label="1:1 line"
)

axes[2].set_xlim(lo, hi)
axes[2].set_ylim(lo, hi)
axes[2].set_xlabel("True LST (°C)")
axes[2].set_ylabel("Predicted LST (°C)")
axes[2].set_title(f"CNN Test R$^2$ = {test_r2:.3f}")
axes[2].grid(True, linestyle="--", alpha=0.3)
axes[2].legend(frameon=False, loc="lower right")

plt.colorbar(
    sc,
    ax=axes[2],
    fraction=0.046,
    pad=0.04,
    label="True LST (°C)"
)

plt.tight_layout()

final_plot = os.path.join(
    OUTPUT_DIR,
    "CNN_no_coordinates_true_predicted_scatter.png"
)

plt.savefig(final_plot, dpi=300, bbox_inches="tight")
plt.show()


# =====================================================
# SAVE PREDICTION MAP AS GEOTIFF
# =====================================================

pred_tif = os.path.join(OUTPUT_DIR, "CNN_no_coordinates_predicted_LST.tif")

pred_profile = lcz_profile.copy()
pred_profile.update(
    dtype=rasterio.float32,
    count=1,
    nodata=np.nan
)

with rasterio.open(pred_tif, "w", **pred_profile) as dst:
    dst.write(pred_map.astype(np.float32), 1)


# =====================================================
# PRINT OUTPUTS
# =====================================================

print("\nSaved outputs:")
print(model_path)
print(metrics_csv)
print(loss_plot)
print(final_plot)
print(pred_tif)

print("\nDone. CNN without coordinate features completed.")

# =====================================================
# FINAL FIGURE: FULL MAP + SCATTER
# =====================================================

def predict_indices(model, flat_indices, batch_size=2048):
    ds = PatchDataset(feature_stack, lst_array, flat_indices, PATCH_SIZE_CNN)
    loader = DataLoader(ds, batch_size=batch_size, shuffle=False, num_workers=0)

    preds, targets = [], []
    model.eval()

    with torch.no_grad():
        for xb, yb in loader:
            xb = xb.to(DEVICE)
            pred = model(xb).cpu().numpy()
            preds.append(pred)
            targets.append(yb.numpy())

    return np.concatenate(preds), np.concatenate(targets)


# Predict FULL valid raster, not only train/val/test
print("Predicting full valid map...")
full_indices = valid_indices
full_preds, full_targets = predict_indices(cnn_model, full_indices, batch_size=2048)

true_map = np.full(lcz_array.shape, np.nan, dtype=np.float32)
pred_map = np.full(lcz_array.shape, np.nan, dtype=np.float32)

rows = full_indices // W
cols = full_indices % W

true_map[rows, cols] = full_targets
pred_map[rows, cols] = full_preds


# Scatter uses train/val/test only
train_preds, train_targets = predict_indices(cnn_model, train_indices)
val_preds, val_targets = predict_indices(cnn_model, val_indices)
test_preds, test_targets = predict_indices(cnn_model, test_indices)

test_r2 = r2_score(test_targets, test_preds)


# Optional: make maps smoother visually
true_show = true_map.copy()
pred_show = pred_map.copy()

vmin = np.nanpercentile(true_show, 2)
vmax = np.nanpercentile(true_show, 98)


# Geographic extent from raster
transform = lcz_profile["transform"]

xmin = transform.c
xmax = transform.c + transform.a * W
ymax = transform.f
ymin = transform.f + transform.e * H

extent = [xmin, xmax, ymin, ymax]


fig, axes = plt.subplots(1, 3, figsize=(18, 5), dpi=300)

# -----------------------------
# True map
# -----------------------------
im0 = axes[0].imshow(
    true_show,
    cmap="Spectral_r",
    vmin=vmin,
    vmax=vmax,
    extent=extent
)

axes[0].set_title("True LST")
axes[0].set_xlabel("Longitude")
axes[0].set_ylabel("Latitude")

plt.colorbar(
    im0,
    ax=axes[0],
    fraction=0.046,
    pad=0.04,
    label="LST (°C)"
)


# -----------------------------
# Predicted map
# -----------------------------
im1 = axes[1].imshow(
    pred_show,
    cmap="Spectral_r",
    vmin=vmin,
    vmax=vmax,
    extent=extent
)

axes[1].set_title("Predicted LST - CNN")
axes[1].set_xlabel("Longitude")
axes[1].set_ylabel("Latitude")

plt.colorbar(
    im1,
    ax=axes[1],
    fraction=0.046,
    pad=0.04,
    label="LST (°C)"
)


# -----------------------------
# Scatter
# -----------------------------
axes[2].scatter(
    train_targets,
    train_preds,
    s=5,
    alpha=0.35,
    label="Train"
)

axes[2].scatter(
    val_targets,
    val_preds,
    s=5,
    alpha=0.45,
    label="Validation"
)

sc = axes[2].scatter(
    test_targets,
    test_preds,
    c=test_targets,
    cmap="Spectral_r",
    s=5,
    alpha=0.65,
    label="Test"
)

lo = min(test_targets.min(), test_preds.min())
hi = max(test_targets.max(), test_preds.max())

axes[2].plot(
    [lo, hi],
    [lo, hi],
    "k--",
    linewidth=1.2,
    label="1:1 line"
)

axes[2].set_xlim(lo, hi)
axes[2].set_ylim(lo, hi)
axes[2].set_xlabel("True LST (°C)")
axes[2].set_ylabel("Predicted LST (°C)")
axes[2].set_title(f"CNN Test R$^2$ = {test_r2:.3f}")
axes[2].grid(True, linestyle="--", alpha=0.3)
axes[2].legend(frameon=False, loc="lower right")

plt.colorbar(
    sc,
    ax=axes[2],
    fraction=0.046,
    pad=0.04,
    label="True LST (°C)"
)

plt.tight_layout()

final_plot = os.path.join(OUTPUT_DIR, "CNN_full_true_predicted_scatter.png")
plt.savefig(final_plot, dpi=300, bbox_inches="tight")
plt.show()

print("Saved final figure:", final_plot)