# -*- coding: utf-8 -*-
"""Another copy of demo_urban_LCZ_LST_GNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-hVJeuOMK_sBr3FIiqGWgGg80znRk4b8
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install rasterio

!pip install torch torchvision torchaudio

!pip install torch-geometric

!pip freeze | grep -E "torch|pyg|scikit|numpy"

import numpy as np
import matplotlib.pyplot as plt
import rasterio
import matplotlib.colors as mcolors
import time
from sklearn.metrics import r2_score
from scipy import ndimage
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.data import Data
from torch_geometric.nn import GATConv
from sklearn.neighbors import NearestNeighbors

import torch, torch_geometric
print(torch.__version__)
print(torch_geometric.__version__)

"""# Data load

# LCZ_before
"""

filename = '/content/drive/MyDrive/LCZ-LST_analysis/LCZ_Urban_CONUS_2020_2km.tif'

with rasterio.open(filename) as src:
    lcz_array = src.read(1)
    lcz_transform = src.transform
    lcz_crs = src.crs
    lcz_bounds = src.bounds

np.unique(lcz_array), lcz_array.shape

lcz_colors = {
    1: '#8B0000',
    2: '#D2042D',
    3: '#FF0000',
    4: '#CC5500',
    5: '#FF8C00',
    6: '#FFB366',
    7: '#0000FF',
    8: '#808080',
    9: '#FFD9B3',
    10: '#696969',
    11: '#006400',
    12: '#228B22',
    13: '#6E8B74',
    14: '#5DBE8A',
    15: '#000000',
    16: '#FFFFCC',
    17: '#9999FF',
}

lcz_labels = {
    1: 'LCZ1',
    2: 'LCZ2',
    3: 'LCZ3',
    4: 'LCZ4',
    5: 'LCZ5',
    6: 'LCZ6',
    7: 'LCZ7',
    8: 'LCZ8',
    9: 'LCZ9',
    10: 'LCZ10',
    11: 'LCZA',
    12: 'LCZB',
    13: 'LCZC',
    14: 'LCZD',
    15: 'LCZE',
    16: 'LCZF',
    17: 'LCZG',
}

cmap = mcolors.ListedColormap([lcz_colors[i] for i in range(1, 18)])
bounds = list(range(1, 19))
norm = mcolors.BoundaryNorm(bounds, cmap.N)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(4, 3), width_ratios=[8, 1])

im = ax1.imshow(lcz_array, cmap=cmap, norm=norm, interpolation='nearest')
ax1.set_title('LCZ Classification - Phoenix', fontsize=10, fontweight='bold')
ax1.axis('off')

legend_elements = []
for lcz_class in np.unique(lcz_array):
    if lcz_class > 0: # Only include LCZ classes with defined labels (i.e., > 0)
        color = lcz_colors.get(lcz_class, '#CCCCCC')
        label = f'{lcz_class}: {lcz_labels[lcz_class]}'
        legend_elements.append(plt.Rectangle((0,0),1,1, facecolor=color, label=label))

ax2.legend(handles=legend_elements, loc='center', fontsize=6,
           title='LCZ Classes', title_fontsize=8)
ax2.axis('off')

plt.tight_layout()
plt.show()

"""## LST"""

filename = '/content/drive/MyDrive/LCZ-LST_analysis/LST_CONUS_2020_2km.tif'

with rasterio.open(filename) as src:
    lst_array = src.read(1)
    lst_transform = src.transform
    lst_crs = src.crs
    lst_bounds = src.bounds

cmap = 'magma'

fig, ax = plt.subplots(1, 1, figsize=(4, 3))

im = ax.imshow(lst_array, cmap=cmap, interpolation='nearest')
ax.set_title('LST - Phoenix', fontsize=10, fontweight='bold')
ax.axis('off')
fig.colorbar(im, ax=ax)

plt.tight_layout()
plt.show()

lst_array.shape

"""# Demo (step by step)"""

import rasterio.warp

# Ensure lcz_array has the same shape as lst_array
# This block addresses the IndexError caused by mismatched array shapes.
if lcz_array.shape != lst_array.shape:
    print(f"Adjusting lcz_array shape from {lcz_array.shape} to match lst_array's shape {lst_array.shape}")
    reprojected_lcz_array = np.empty_like(lst_array, dtype=lcz_array.dtype)
    rasterio.warp.reproject(
        source=lcz_array,
        src_transform=lcz_transform,
        src_crs=lcz_crs,
        destination=reprojected_lcz_array,
        dst_transform=lst_transform,
        dst_crs=lst_crs,
        resampling=rasterio.warp.Resampling.nearest, # Use nearest neighbor for categorical data
        num_threads=4
    )
    lcz_array = reprojected_lcz_array
    print(f"Lcz_array's new shape: {lcz_array.shape}")

# Handle potential NaNs or 0s after reprojection, and ensure float type for NaN support
lcz_array = np.where(lcz_array == 0, np.nan, lcz_array)
lcz_array = np.round(lcz_array).astype(float)


print("=== avg temperature for each LCZ ===")
# Iterate over non-NaN unique LCZ classes to prevent errors with np.unique on array with NaNs
for lcz_class in np.unique(lcz_array[~np.isnan(lcz_array)]):
    lcz_class_int = int(lcz_class) # Convert to int for comparison and formatting
    if lcz_class_int > 0 and lcz_class_int <= 17:
        mask = (lcz_array == lcz_class_int)
        # Check if there are any valid pixels for this LCZ class after masking
        if np.sum(mask) > 0:
            # Calculate mean temperature, ignoring NaNs in LST for valid pixels
            mean_temp = np.nanmean(lst_array[mask])
            print(f"LCZ {lcz_class_int:2d}: {mean_temp:.2f} degree C (# of pixels: {np.sum(mask)})")

import rasterio.warp

print(f"Original lcz_array shape: {lcz_array.shape}")
print(f"Original lst_array shape: {lst_array.shape}")

# Reproject lcz_array to match lst_array's characteristics
reprojected_lcz_array = np.empty_like(lst_array, dtype=lcz_array.dtype)

rasterio.warp.reproject(
    source=lcz_array,
    src_transform=lcz_transform,
    src_crs=lcz_crs,
    destination=reprojected_lcz_array,
    dst_transform=lst_transform,
    dst_crs=lst_crs,
    resampling=rasterio.warp.Resampling.nearest, # Use nearest neighbor for categorical data (LCZ classes)
    num_threads=4 # Use multiple threads for faster processing
)

lcz_array = reprojected_lcz_array

print(f"Resampled lcz_array shape: {lcz_array.shape}")

# Replace any potential fill values with 0 or NaN if necessary
# Assuming that original LCZ values are > 0, 0 can be treated as 'no data'
# For further calculations, it might be better to treat them as NaN.
# Let's replace 0s (if introduced by reprojection outside original extent) with NaN for clarity in analysis.
lcz_array = np.where(lcz_array == 0, np.nan, lcz_array)

# Verify that the LCZ classes are still integers, converting if necessary
lcz_array = np.round(lcz_array).astype(float) # Cast to float to allow NaNs

# Re-run the average temperature calculation
print("=== avg and std temperature for each LCZ ===")
for lcz_class in np.unique(lcz_array[~np.isnan(lcz_array)]): # Iterate over non-NaN unique LCZ classes
    lcz_class = int(lcz_class) # Ensure LCZ class is integer
    if lcz_class > 0 and lcz_class <= 17:
        mask = (lcz_array == lcz_class)
        # Apply mask only where LST data is also valid (not NaN)
        valid_temp_pixels = lst_array[mask & ~np.isnan(lst_array)]
        if valid_temp_pixels.size > 0:
            mean_temp = np.mean(valid_temp_pixels)
            std_temp = np.std(valid_temp_pixels)
            print(f"LCZ {lcz_class:2d}: Mean={mean_temp:.2f} C, Std={std_temp:.2f} C (# of pixels: {valid_temp_pixels.size})")

"""## Calculate index"""

def calculate_PLAND(lcz_array, window_size, lcz_classes=range(1, 18)):
    """
    for each LCZ class, calculate the percentage of its area within the window around each pixel
    """

    PLAND_features = np.zeros((lcz_array.shape[0], lcz_array.shape[1], len(lcz_classes)))

    for i, lcz_class in enumerate(lcz_classes):
        binary_mask = (lcz_array == lcz_class).astype(float)
        PLAND_features[:, :, i] = ndimage.uniform_filter(binary_mask, size=window_size)

    return PLAND_features

def calculate_CONTAG(lcz_array, window_size):
    """
    Contagion to measure the extent to which patch types are aggregated or clumped
    probability that two adjacent pixels belong to the same class
    """
    H, W = lcz_array.shape
    CONTAG_map = np.zeros((H, W))

    half_window = window_size // 2
    m = len(np.unique(lcz_array))

    for i in range(H):
        for j in range(W):
            i_start = max(0, i - half_window)
            i_end = min(H, i + half_window + 1)
            j_start = max(0, j - half_window)
            j_end = min(W, j + half_window + 1)

            window = lcz_array[i_start:i_end, j_start:j_end]

            total_pairs = 0
            same_class_pairs = 0

            for x in range(window.shape[0]):
                for y in range(window.shape[1] - 1):
                    if window[x, y] == window[x, y + 1]:
                        same_class_pairs += 1
                    total_pairs += 1

            for x in range(window.shape[0] - 1):
                for y in range(window.shape[1]):
                    if window[x, y] == window[x + 1, y]:
                        same_class_pairs += 1
                    total_pairs += 1

            if total_pairs > 0:
                p_same = same_class_pairs / total_pairs
                CONTAG_map[i, j] = 1 + (p_same * np.log(p_same + 1e-8) +
                                      (1-p_same) * np.log(1-p_same + 1e-8)) / (2 * np.log(m))
            else:
                CONTAG_map[i, j] = 0

    return np.clip(CONTAG_map, 0, 1)

def calculate_SHDI(lcz_array, window_size):
    """
    Shannon Diversity Index, also known as the Shannon-Wiener index
    a measure of biodiversity that quantifies both the species richness (number of different species)
    and the evenness (abundance of each species) within a community.
    --> we use that to measure the richness and evenness of LCZ classes within each window for each pixel
    --> higher values indicate more diverse LCZ types
    It is calculated using the formula H = - sum p_i * ln(p_i)
    """

    def shannon_diversity(window):
        unique, counts = np.unique(window, return_counts=True)
        proportions = counts / counts.sum()
        return -np.sum(proportions * np.log(proportions + 1e-8))

    shdi_map = ndimage.generic_filter(lcz_array, shannon_diversity, size=window_size)
    return shdi_map

def calculate_SHAPE_AM(lcz_array, window_size):
    """
    area-weighted mean shape index, measure complexity of patch shapes
    a value of 1 indicates a square; larger values ​​indicate more complex and irregular shapes
    """
    from skimage import measure

    H, W = lcz_array.shape
    shape_map = np.zeros((H, W))

    half_window = window_size // 2
    for i in range(half_window, H - half_window):
        for j in range(half_window, W - half_window):
            window = lcz_array[i-half_window:i+half_window+1, j-half_window:j+half_window+1]
            total_shape_index = 0
            total_area = 0

            for lcz_class in np.unique(window):
                if lcz_class > 0:
                    binary_mask = (window == lcz_class)
                    if binary_mask.sum() > 0:
                        contours = measure.find_contours(binary_mask, 0.5)
                        for contour in contours:
                            perimeter = len(contour)
                            area = binary_mask.sum()
                            if area > 0 and perimeter > 0:
                                shape_idx = perimeter / (4 * np.sqrt(area))
                                total_shape_index += shape_idx * area
                                total_area += area

            if total_area > 0:
                shape_map[i, j] = total_shape_index / total_area

    return shape_map

import os

output_dir = '../image'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)
    print(f"Created directory: {output_dir}")
else:
    print(f"Directory already exists: {output_dir}")

def calculate_TECI(lcz_array, window_size):
    """Total Edge Contrast Index to measure contrast between adjacent patch types"""
    H, W = lcz_array.shape
    TECI_map = np.zeros((H, W))

    half_window = window_size // 2

    def get_contrast_weight(class1, class2):
        built1 = 1 <= class1 <= 10
        built2 = 1 <= class2 <= 10
        natural1 = 11 <= class1 <= 17
        natural2 = 11 <= class2 <= 17

        if (built1 and built2) or (natural1 and natural2):
            return 0.0
        elif (built1 and natural2) or (natural1 and built2):
            return 1.0
        else:
            return 0.5

    for i in range(half_window, H - half_window):
        for j in range(half_window, W - half_window):
            window = lcz_array[i-half_window:i+half_window+1, j-half_window:j+half_window+1]

            total_contrast = 0
            total_edges = 0

            for x in range(window.shape[0]):
                for y in range(window.shape[1] - 1):
                    contrast = get_contrast_weight(window[x, y], window[x, y + 1])
                    total_contrast += contrast
                    total_edges += 1

            for x in range(window.shape[0] - 1):
                for y in range(window.shape[1]):
                    contrast = get_contrast_weight(window[x, y], window[x + 1, y])
                    total_contrast += contrast
                    total_edges += 1

            if total_edges > 0:
                TECI_map[i, j] = total_contrast / total_edges
            else:
                TECI_map[i, j] = 0

    return TECI_map

def calculate_AI(lcz_array, window_size):
    """
    Aggregation Index to measure degree of aggregation of patches
    """
    H, W = lcz_array.shape
    AI_map = np.zeros((H, W))

    half_window = window_size // 2

    for i in range(half_window, H - half_window):
        for j in range(half_window, W - half_window):
            window = lcz_array[i-half_window:i+half_window+1, j-half_window:j+half_window+1]

            max_possible_edges = 0
            actual_edges = 0

            for x in range(window.shape[0]):
                for y in range(window.shape[1] - 1):
                    max_possible_edges += 1
                    if window[x, y] == window[x, y + 1]:
                        actual_edges += 1

            for x in range(window.shape[0] - 1):
                for y in range(window.shape[1]):
                    max_possible_edges += 1
                    if window[x, y] == window[x + 1, y]:
                        actual_edges += 1

            if max_possible_edges > 0:
                AI_map[i, j] = actual_edges / max_possible_edges
            else:
                AI_map[i, j] = 0

    return AI_map

def calculate_PD(lcz_array, window_size):
    """
    Patch Density to measure number of different patch types per unit area
    """
    def count_patches(window):
        unique_classes = np.unique(window)
        valid_classes = [c for c in unique_classes if 1 <= c <= 17]
        return len(valid_classes)

    PD_map = ndimage.generic_filter(lcz_array, count_patches, size=window_size)
    PD_map = PD_map / (window_size * window_size)
    return PD_map

def calculate_contagion_fast(lcz_array, window_size):
    from itertools import product

    H, W = lcz_array.shape
    contag_map = np.zeros((H, W))
    unique_classes = np.unique(lcz_array)
    m = len(unique_classes)

    if m <= 1:
        return contag_map

    half_window = window_size // 2

    class_pairs = list(product(unique_classes, repeat=2))

    for i in range(half_window, H - half_window):
        for j in range(half_window, W - half_window):
            window = lcz_array[i-half_window:i+half_window+1, j-half_window:j+half_window+1]

            horizontal_diff = window[:, :-1] != window[:, 1:]
            h_same_pairs = np.sum(~horizontal_diff)
            h_total_pairs = horizontal_diff.size

            vertical_diff = window[:-1, :] != window[1:, :]
            v_same_pairs = np.sum(~vertical_diff)
            v_total_pairs = vertical_diff.size

            total_pairs = h_total_pairs + v_total_pairs
            same_pairs = h_same_pairs + v_same_pairs

            if total_pairs == 0:
                contag_map[i, j] = 0
                continue

            p_same = same_pairs / total_pairs
            p_diff = 1 - p_same

            if p_same > 0 and p_diff > 0:
                contag = p_same * np.log(p_same) + p_diff * np.log(p_diff)
                contag = 1 + contag / (2 * np.log(m))
                contag_map[i, j] = max(0, min(1, contag))
            else:
                contag_map[i, j] = 1 if p_same == 1 else 0

    return contag_map

def calculate_all_landscape_metrics(lcz_array, window_size=15):
    """Calculate all standard landscape metrics"""
    print("Calculating standard landscape metrics...")

    metrics = {
        'PLAND': calculate_PLAND(lcz_array, window_size),
        'CONTAG': calculate_CONTAG(lcz_array, window_size),
        'SHAPE_AM': calculate_SHAPE_AM(lcz_array, window_size),
        'SHDI': calculate_SHDI(lcz_array, window_size),
        'PD': calculate_PD(lcz_array, window_size),
        'AI': calculate_AI(lcz_array, window_size),
        'TECI': calculate_TECI(lcz_array, window_size)
    }

    print("Landscape metrics calculation completed!")
    return metrics

"""## Construct data"""

def create_enriched_graph_from_rasters(lcz_array, lst_array, landscape_metrics, k_neighbors=8):
    """Create graph with enriched node features including landscape metrics"""

    H, W = lcz_array.shape

    rows, cols = np.meshgrid(np.arange(H), np.arange(W), indexing='ij')
    coords = np.column_stack([rows.ravel(), cols.ravel()])

    lcz_flat = lcz_array.ravel()
    lst_flat = lst_array.ravel()

    valid_mask = (lcz_array > 0) & (lcz_array <= 17) & ~np.isnan(lst_array)
    valid_indices = np.where(valid_mask.ravel())[0]

    print(f"Number of valid nodes: {len(valid_indices)}")

    valid_coords = coords[valid_indices]
    valid_lcz = lcz_flat[valid_indices]
    valid_lst = lst_flat[valid_indices]

    knn = NearestNeighbors(n_neighbors=k_neighbors+1, algorithm='auto')
    knn.fit(valid_coords)
    distances, indices = knn.kneighbors(valid_coords)

    src = np.repeat(np.arange(len(valid_coords)), k_neighbors)
    dst = indices[:, 1:].reshape(-1)

    edge_index = torch.tensor([src, dst], dtype=torch.long)

    edge_distances = distances[:, 1:].reshape(-1, 1)
    lcz_similarity = 1.0 - (np.abs(valid_lcz[src] - valid_lcz[dst]) / 17.0).reshape(-1, 1)

    edge_attr = torch.tensor(
        np.concatenate([edge_distances, lcz_similarity], axis=1),
        dtype=torch.float32
    )

    node_features = []

    existing_lcz_classes = np.unique(valid_lcz)

    for idx, (i, j) in enumerate(valid_coords):
        feature_vector = [
            landscape_metrics['CONTAG'][i, j],           # Contagion index
            landscape_metrics['SHDI'][i, j],             # Shannon diversity index
            landscape_metrics['SHAPE_AM'][i, j],         # Shape index
            landscape_metrics['TECI'][i, j],             # Total edge contrast index
            landscape_metrics['AI'][i, j],               # Aggregation index
            landscape_metrics['PD'][i, j],               # Patch density
        ]

        # add PLAND features - only the node's own LCZ class gets 1, others get actual PLAND values
        current_lcz_class = int(valid_lcz[idx])
        for lcz_class in range(1, 18):
            if lcz_class in existing_lcz_classes:
                if lcz_class == current_lcz_class:
                    # for the node's own LCZ class, use one-hot encoding (1.0)
                    feature_vector.append(1.0)
                else:
                    # for other LCZ classes, use the actual PLAND value
                    feature_vector.append(landscape_metrics['PLAND'][i, j, lcz_class-1])

        node_features.append(feature_vector)

    x = torch.tensor(node_features, dtype=torch.float32)
    y = torch.tensor(valid_lst, dtype=torch.float32).reshape(-1, 1)

    return x, y, edge_index, edge_attr, valid_indices

def get_feature_names(lcz_array):
    """Generate complete feature names list"""
    base_names = [
        'CONTAG',
        'SHDI',
        'SHAPE_AM',
        'TECI',
        'AI',
        'PD'
    ]

    existing_lcz = np.unique(lcz_array)
    pland_names = [f'PLAND_LCZ_{int(lcz_class)}' for lcz_class in existing_lcz if lcz_class > 0]

    return base_names + pland_names

"""### Choose window size (can adjust this)"""

window_size = 3
landscape_metrics = calculate_all_landscape_metrics(lcz_array, window_size)

x, y, edge_index, edge_attr, valid_indices = create_enriched_graph_from_rasters(
    lcz_array, lst_array, landscape_metrics, k_neighbors=8
    )

feature_names = get_feature_names(lcz_array)

data = Data(
    x=x,                    # enriched node features [position + all_landscape_metrics]
    y=y,                    # target LST values
    edge_index=edge_index,  # graph connectivity
    edge_attr=edge_attr,    # edge features [distance, lcz_similarity]
    num_nodes=x.size(0)
)

print(f"Enriched Data object created successfully!")
print(f"Node features shape: {data.x.shape}")
print(f"Number of features: {len(feature_names)}")
print(f"Feature names: {feature_names}")

print(f"\n=== Data Verification ===")
print(f"Number of nodes: {data.num_nodes}")
print(f"Number of edges: {data.edge_index.shape[1]}")
print(f"Node feature range: [{data.x.min():.3f}, {data.x.max():.3f}]")
print(f"Target value range: [{data.y.min():.3f}, {data.y.max():.3f}]")

"""## Model"""

class SimpleGAT(nn.Module):
    def __init__(self, node_in_dim, hidden_dim, heads, dropout=0.2):
        super().__init__()

        self.gat1 = GATConv(node_in_dim, hidden_dim, heads=heads, dropout=dropout)
        self.gat2 = GATConv(hidden_dim * heads, hidden_dim, heads=1, dropout=dropout, concat=False)

        self.output = nn.Linear(hidden_dim, 1)
        self.dropout = dropout

        self.attention_weights = None

    def forward(self, data, return_attention=False):
        x, edge_index = data.x, data.edge_index

        x, att1 = self.gat1(x, edge_index, return_attention_weights=True)
        x = F.elu(x)
        x = F.dropout(x, p=self.dropout, training=self.training)

        x, att2 = self.gat2(x, edge_index, return_attention_weights=True)
        x = F.elu(x)

        if return_attention:
            self.attention_weights = (att1, att2)

        out = self.output(x)
        return out.squeeze()

def train_simple_model(model, data, epochs, lr):
    """Better training function"""
    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=1e-5)
    criterion = nn.MSELoss()

    train_losses = []
    val_losses = []

    for epoch in range(epochs):
        start = time.time()
        model.train()
        optimizer.zero_grad()

        out = model(data)
        loss = criterion(out[data.train_mask], data.y[data.train_mask].squeeze())

        loss.backward()
        optimizer.step()

        model.eval()
        with torch.no_grad():
            val_out = model(data)
            val_loss = criterion(val_out[data.val_mask], data.y[data.val_mask].squeeze())

        train_losses.append(loss.item())
        val_losses.append(val_loss.item())

        if epoch % 50 == 0:
            print(f'epoch {epoch:03d}, train loss: {loss:.4f}, val loss: {val_loss:.4f}, time cost: {time.time()-start:.4f}s')

    return train_losses, val_losses

def evaluate_model_simple(model, data, mask):
    """Proper evaluation"""
    model.eval()
    with torch.no_grad():
        predictions = model(data)[mask].cpu().numpy()
        targets = data.y[mask].cpu().numpy().squeeze()

        mse = ((predictions - targets) ** 2).mean()
        rmse = np.sqrt(mse)
        mae = np.abs(predictions - targets).mean()
        r2 = 1 - ((predictions - targets) ** 2).sum() / ((targets - targets.mean()) ** 2).sum()

        print(f"RMSE: {rmse:.4f}")
        print(f"MAE:  {mae:.4f}")
        print(f"R²:   {r2:.4f}")

        return predictions, targets

class SimpleAnalyzer:
    def __init__(self, model, data, feature_names, original_shape):
        self.model = model
        self.data = data
        self.feature_names = feature_names
        self.original_shape = original_shape

    def analyze_feature_importance(self):
        """Simple feature importance based on input layer weights"""
        if hasattr(self.model, 'node_encoder'):
            weights = self.model.node_encoder.weight.data.cpu().numpy()
        else:
            try:
                if hasattr(self.model.gat1, 'lin'):
                    weights = self.model.gat1.lin.weight.data.cpu().numpy()
                elif hasattr(self.model.gat1, 'weight'):
                    weights = self.model.gat1.weight.data.cpu().numpy()
                else:
                    print("Cannot access GAT layer weights directly")
                    return {}
            except:
                print("Failed to access model weights")
                return {}

        importance = np.mean(np.abs(weights), axis=0)

        min_len = min(len(importance), len(self.feature_names))
        return dict(zip(self.feature_names[:min_len], importance[:min_len]))

def get_feature_importance_alternative(model, data, feature_names):
    model.eval()

    with torch.no_grad():
        baseline_pred = model(data)
        baseline_loss = F.mse_loss(baseline_pred[data.val_mask], data.y[data.val_mask].squeeze()).item()

    importance_scores = {}

    for i, feature_name in enumerate(feature_names):
        if i >= data.x.size(1):
            break

        original_feature = data.x[:, i].clone()

        shuffled_indices = torch.randperm(data.x.size(0))
        data.x[:, i] = data.x[shuffled_indices, i]

        with torch.no_grad():
            shuffled_pred = model(data)
            shuffled_loss = F.mse_loss(shuffled_pred[data.val_mask], data.y[data.val_mask].squeeze()).item()

        data.x[:, i] = original_feature

        importance_scores[feature_name] = shuffled_loss - baseline_loss

    return importance_scores

"""## Train"""

seed = 8
np.random.seed(seed)
torch.cuda.manual_seed(seed)
torch.manual_seed(seed)
torch.backends.cudnn.deterministic = True

def create_spatial_split(data, seed, train_ratio=0.7, val_ratio=0.1):
    torch.manual_seed(seed)
    n_nodes = data.num_nodes
    indices = torch.randperm(n_nodes)

    n_train = int(n_nodes * train_ratio)
    n_val = int(n_nodes * val_ratio)

    train_mask = torch.zeros(n_nodes, dtype=torch.bool)
    val_mask = torch.zeros(n_nodes, dtype=torch.bool)
    test_mask = torch.zeros(n_nodes, dtype=torch.bool)

    train_mask[indices[:n_train]] = True
    val_mask[indices[n_train:n_train+n_val]] = True
    test_mask[indices[n_train+n_val:]] = True

    return train_mask, val_mask, test_mask

train_mask, val_mask, test_mask = create_spatial_split(data, seed=seed)
data.train_mask = train_mask
data.val_mask = val_mask
data.test_mask = test_mask

print(f"\n=== Data Split ===")
print(f"Training nodes: {train_mask.sum().item()} ({train_mask.sum().item()/data.num_nodes*100:.1f}%)")
print(f"Validation nodes: {val_mask.sum().item()} ({val_mask.sum().item()/data.num_nodes*100:.1f}%)")
print(f"Test nodes: {test_mask.sum().item()} ({test_mask.sum().item()/data.num_nodes*100:.1f}%)")

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

hidden_dim, heads = 64, 8

model = SimpleGAT(node_in_dim=data.x.size(1), hidden_dim=hidden_dim, heads=heads)
model = model.to(device)

data = data.to(device)


# #=================================================
# '''finetune with pre-train'''
# PATH = '../model/'
# p = 'demo_GNN_LCZ2LST_hidden_size_64_window_size_9.pt'
# state_dict = torch.load(PATH+p)
# model.load_state_dict(state_dict, strict=True)
# #=================================================


pytorch_total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print('Total number of trainable parameters:', pytorch_total_params)

for name, param in model.named_parameters():
    if param.requires_grad:
        print(f"{name}: {tuple(param.shape)}")

print("Training simple GAT...")
train_losses, val_losses = train_simple_model(model, data, epochs=1000, lr=1e-2)

plt.figure(figsize=(5, 3))
plt.plot(train_losses, label='train')
plt.plot(val_losses, label='test')
plt.legend()
plt.show()
print('Done!')

"""## Save the model"""

PATH = '/content/drive/MyDrive/LST_LCZ'
p = 'demo_GNN_LCZ_hidden_size_%s_window_size_%s.pt' %(hidden_dim, window_size)
torch.save(model.state_dict(), PATH+p)

"""# Load the model"""

PATH = '/content/drive/MyDrive/LST_LCZ' # Added trailing slash
p = 'demo_GNN_LCZ_hidden_size_%s_window_size_%s.pt' % (hidden_dim, window_size) # Corrected formatting
state_dict = torch.load(PATH+p)
model.load_state_dict(state_dict, strict=True)

"""## Evaluate the model"""

print("\n=== Test Performance ===")
test_predictions, test_targets = evaluate_model_simple(model, data, data.test_mask)

import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap, BoundaryNorm, Normalize
from matplotlib.cm import ScalarMappable
from sklearn.metrics import r2_score
import numpy as np
import torch


def make_lst_like_cmap():
    colors = [
        "#2b6cb0",  # deep blue
        "#5fa8d3",  # blue-cyan
        "#9dd9d2",  # light cyan
        "#f3e79b",  # pale yellow
        "#f6c667",  # yellow-orange
        "#ee8f39",  # orange
        "#d84b2a",  # red-orange
        "#b2182b",  # deep red
    ]
    cmap = ListedColormap(colors, name="lst_like")
    return cmap

def make_bounds_from_data(values, n_classes=8):
    vmin = np.nanmin(values)
    vmax = np.nanmax(values)

    lo = np.floor(vmin / 5.0) * 5.0
    hi = np.ceil(vmax / 5.0) * 5.0

    bounds = np.linspace(lo, hi, n_classes + 1)
    return bounds

def nodes_to_full_map(node_values, valid_indices, original_shape):
    out = np.full(original_shape, np.nan, dtype=float)
    rows, cols = np.unravel_index(valid_indices, original_shape)
    out[rows, cols] = node_values
    return out

def build_prediction_rgba_map(
    pred_all,
    valid_indices,
    original_shape,
    norm,
    cmap,
    train_mask,
    test_mask,
    val_mask=None,
    train_alpha=0.5,
    test_alpha=1.0,
    val_alpha=0.35,
    include_val_as_context=True,
):
    H, W = original_shape
    rgba = np.zeros((H, W, 4), dtype=float)

    rows, cols = np.unravel_index(valid_indices, original_shape)

    train_idx = np.where(train_mask.cpu().numpy())[0]
    if len(train_idx) > 0:
        train_colors = cmap(norm(pred_all[train_idx]))
        train_colors[:, 3] = train_alpha
        rgba[rows[train_idx], cols[train_idx], :] = train_colors

    if include_val_as_context and (val_mask is not None):
        val_idx = np.where(val_mask.cpu().numpy())[0]
        if len(val_idx) > 0:
            val_colors = cmap(norm(pred_all[val_idx]))
            val_colors[:, 3] = val_alpha
            rgba[rows[val_idx], cols[val_idx], :] = val_colors

    test_idx = np.where(test_mask.cpu().numpy())[0]
    if len(test_idx) > 0:
        test_colors = cmap(norm(pred_all[test_idx]))
        test_colors[:, 3] = test_alpha
        rgba[rows[test_idx], cols[test_idx], :] = test_colors

    return rgba

def plot_results_1x3(
    model,
    data,
    valid_indices,
    original_shape,
    bounds=None,
    train_alpha=0.5,
    test_alpha=1.0,
    val_alpha=0.5,
    include_val_as_context=True,
    figsize=(15, 4.8),
    dpi=300,
    lon_range=None,
    lat_range=None,
    lon_array=None,
    lat_array=None,
    use_continuous_cmap=True,
    save_fig=None
):
    device = next(model.parameters()).device
    model.eval()

    with torch.no_grad():
        pred_all = model(data).detach().cpu().numpy().reshape(-1)

    y_all = data.y.detach().cpu().numpy().reshape(-1)

    all_values = np.concatenate((y_all, pred_all))

    if use_continuous_cmap:
        vmin = np.nanmin(all_values)
        vmax = np.nanmax(all_values)

        from matplotlib.colors import LinearSegmentedColormap
        colors = [
            "#2b6cb0",  # deep blue
            "#5fa8d3",  # blue-cyan
            "#9dd9d2",  # light cyan
            "#f3e79b",  # pale yellow
            "#f6c667",  # yellow-orange
            "#ee8f39",  # orange
            "#d84b2a",  # red-orange
            "#b2182b",  # deep red
        ]
        cmap = LinearSegmentedColormap.from_list("lst_like_continuous", colors, N=256)
        norm = Normalize(vmin=vmin, vmax=vmax)
        bounds_for_cbar = np.linspace(vmin, vmax, 9)
    else:
        if bounds is None:
            bounds = make_bounds_from_data(all_values, n_classes=8)
        bounds = np.asarray(bounds, dtype=float)
        cmap = make_lst_like_cmap()
        norm = BoundaryNorm(bounds, cmap.N, clip=True)
        bounds_for_cbar = bounds

    true_map = nodes_to_full_map(y_all, valid_indices, original_shape)

    pred_rgba = build_prediction_rgba_map(
        pred_all=pred_all,
        valid_indices=valid_indices,
        original_shape=original_shape,
        norm=norm,
        cmap=cmap,
        train_mask=data.train_mask,
        test_mask=data.test_mask,
        val_mask=getattr(data, "val_mask", None),
        train_alpha=train_alpha,
        test_alpha=test_alpha,
        val_alpha=val_alpha,
        include_val_as_context=include_val_as_context,
    )

    test_idx = data.test_mask.cpu().numpy()
    test_targets = y_all[test_idx]
    test_predictions = pred_all[test_idx]
    test_r2 = r2_score(test_targets, test_predictions)

    train_idx = data.train_mask.cpu().numpy()
    train_targets = y_all[train_idx]
    train_predictions = pred_all[train_idx]

    val_idx = data.val_mask.cpu().numpy()
    val_targets = y_all[val_idx]
    val_predictions = pred_all[val_idx]
    val_r2 = r2_score(val_targets, val_predictions)

    fig, axes = plt.subplots(1, 3, figsize=figsize, dpi=dpi)

    im0 = axes[0].imshow(
        true_map,
        cmap=cmap,
        norm=norm,
        interpolation="nearest"
    )
    axes[0].set_title("True LST")
    axes[0].grid('on', linestyle='--', color='gray', alpha=.75, linewidth=.5)

    if lon_range is not None and lat_range is not None and lon_array is not None and lat_array is not None:
        lon_min, lon_max = lon_range
        lat_min, lat_max = lat_range

        lon_edges = np.linspace(0, original_shape[1]-1, 4, dtype=int)
        lat_edges = np.linspace(0, original_shape[0]-1, 4, dtype=int)

        lon_positions = lon_array[0, lon_edges]
        lat_positions = lat_array[lat_edges, 0]

        axes[0].set_xticks(lon_edges)
        axes[0].set_xticklabels([f"{lon:.1f}$^\circ$" for lon in lon_positions])
        axes[0].set_yticks(lat_edges)
        axes[0].set_yticklabels([f"{lat:.1f}$^\circ$" for lat in lat_positions])

        axes[0].set_xlabel("Longitude", fontsize=12)
        axes[0].set_ylabel("Latitude", fontsize=12)
    else:
        axes[0].set_xticks(())
        axes[0].set_yticks(())

    cbar0 = plt.colorbar(im0, ax=axes[0], fraction=0.046, pad=0.04)
    cbar0.set_label("LST ($^\circ$C)")
    if not use_continuous_cmap:
        cbar0.set_ticks(bounds_for_cbar)
    cbar0.ax.tick_params(labelsize=8)

    axes[1].imshow(pred_rgba, interpolation="nearest")
    axes[1].set_title("Predicted LST")
    axes[1].grid('on', linestyle='--', color='gray', alpha=.75, linewidth=.5)

    if lon_range is not None and lat_range is not None and lon_array is not None and lat_array is not None:
        axes[1].set_xticks(lon_edges)
        axes[1].set_xticklabels([f"{lon:.1f}$^\circ$" for lon in lon_positions])
        axes[1].set_yticks(lat_edges)
        axes[1].set_yticklabels([f"{lat:.1f}$^\circ$" for lat in lat_positions])
        axes[1].set_xlabel("Longitude", fontsize=12)
        axes[1].set_ylabel("Latitude", fontsize=12)
    else:
        axes[1].set_xticks(())
        axes[1].set_yticks(())

    sm = ScalarMappable(cmap=cmap, norm=norm)
    sm.set_array([])
    cbar1 = plt.colorbar(sm, ax=axes[1], fraction=0.046, pad=0.04)
    cbar1.set_label("LST ($^\circ$C)")
    if not use_continuous_cmap:
        cbar1.set_ticks(bounds_for_cbar)
    cbar1.ax.tick_params(labelsize=8)

    norm_scatter = norm if use_continuous_cmap else BoundaryNorm(bounds, cmap.N, clip=True)

    train_colors = cmap(norm_scatter(train_targets))
    val_colors = cmap(norm_scatter(val_targets))
    test_colors = cmap(norm_scatter(test_targets))

    scatter_train = axes[2].scatter(
        train_targets,
        train_predictions,
        s=6,
        alpha=0.6,
        c=train_targets,
        cmap=cmap,
        norm=norm_scatter,
        label="Train"
    )
    scatter_val = axes[2].scatter(
        val_targets,
        val_predictions,
        s=8,
        alpha=0.75,
        c=val_targets,
        cmap=cmap,
        norm=norm_scatter,
        label="Validation"
    )
    scatter_test = axes[2].scatter(
        test_targets,
        test_predictions,
        s=8,
        alpha=1.,
        c=test_targets,
        cmap=cmap,
        norm=norm_scatter,
        label="Test"
    )

    lo = min(np.nanmin(y_all), np.nanmin(pred_all))
    hi = max(np.nanmax(y_all), np.nanmax(pred_all))
    axes[2].plot((lo, hi), (lo, hi), linestyle="--", color="k", linewidth=1.2, label="1:1 line")

    axes[2].grid('on', linestyle='--', color='gray', alpha=.2)

    axes[2].set_xlabel("True LST ($^\circ$C)", fontsize=12)
    axes[2].set_ylabel("Predicted LST ($^\circ$C)", fontsize=12)
    axes[2].set_title(f"Test R$^2$ = {test_r2:.3f}")

    cbar2 = plt.colorbar(scatter_test, ax=axes[2], fraction=0.046, pad=0.04)
    cbar2.set_label("True LST ($^\circ$C)")
    if not use_continuous_cmap:
        cbar2.set_ticks(bounds_for_cbar)
    cbar2.ax.tick_params(labelsize=8)

    axes[2].legend(frameon=False, loc='lower right')

    plt.tight_layout()

    if save_fig != None:
        fig.savefig(save_fig, dpi=dpi, bbox_inches="tight", transparent=True)
    plt.show()

    return {
        "true_map": true_map,
        "pred_all": pred_all,
        "test_targets": test_targets,
        "test_predictions": test_predictions,
        "bounds": bounds if not use_continuous_cmap else np.linspace(vmin, vmax, 9),
        "test_r2": test_r2,
        "vmin": vmin if use_continuous_cmap else None,
        "vmax": vmax if use_continuous_cmap else None,
    }


lon_array = np.linspace(-113, -111.5, lcz_array.shape[1])
lat_array = np.linspace(32.5, 34, lcz_array.shape[0])
lon_grid, lat_grid = np.meshgrid(lon_array, lat_array)

custom_bounds = (12, 15, 20, 25, 30, 35, 40, 43, 47)

results = plot_results_1x3(
    model=model,
    data=data,
    valid_indices=valid_indices,
    original_shape=lcz_array.shape,
    bounds=custom_bounds,
    train_alpha=0.6,
    test_alpha=1.0,
    val_alpha=0.75,
    include_val_as_context=True,
    figsize=(16, 5),
    dpi=300,
    lon_range=(-113, -111.5),
    lat_range=(32.5, 34),
    lon_array=lon_grid,
    lat_array=lat_grid,
    use_continuous_cmap=True, # <- Negar: if you would like to get a discrete colormap, turn it to "False"
    save_fig='../image/true_predicted_LST_scatter.png' # <- IMPORTANT: Negar, change this path to your own path
)